Ext.define('JCertifBO.store.Countries', {
	extend : 'Ext.data.Store',
	fields: ['cid', 'country'],
  data: [
      {cid: 'Afghanistan' , country: 'Afghanistan' },
      {cid: 'Albania' , country: 'Albania' },
      {cid: 'Algeria' , country: 'Algeria' },
      {cid: 'Andorra' , country: 'Andorra' },
      {cid: 'Angola' , country: 'Angola' },
      {cid: 'Antigua and Barbuda' , country: 'Antigua and Barbuda' },
      {cid: 'Argentina' , country: 'Argentina' },
      {cid: 'Armenia' , country: 'Armenia' },
      {cid: 'Australia' , country: 'Australia' },
      {cid: 'Austria' , country: 'Austria' },
      {cid: 'Azerbaijan' , country: 'Azerbaijan' },
      {cid: 'Bahamas' , country: 'Bahamas' },
      {cid: 'Bahrain' , country: 'Bahrain' },
      {cid: 'Bangladesh' , country: 'Bangladesh' },
      {cid: 'Barbados' , country: 'Barbados' },
      {cid: 'Belarus' , country: 'Belarus' },
      {cid: 'Belgium' , country: 'Belgium' },
      {cid: 'Belize' , country: 'Belize' },
      {cid: 'Benin' , country: 'Benin' },
      {cid: 'Bhutan' , country: 'Bhutan' },
      {cid: 'Bolivia' , country: 'Bolivia' },
      {cid: 'Bosnia and Herzegovina' , country: 'Bosnia and Herzegovina' },
      {cid: 'Botswana' , country: 'Botswana' },
      {cid: 'Brazil' , country: 'Brazil' },
      {cid: 'Brunei' , country: 'Brunei' },
      {cid: 'Bulgaria' , country: 'Bulgaria' },
      {cid: 'Burkina Faso' , country: 'Burkina Faso' },
      {cid: 'Burma' , country: 'Burma' },
      {cid: 'Burundi' , country: 'Burundi' },
      {cid: 'Cambodia' , country: 'Cambodia' },
      {cid: 'Cameroon' , country: 'Cameroon' },
      {cid: 'Canada' , country: 'Canada' },
      {cid: 'Cape Verde' , country: 'Cape Verde' },
      {cid: 'Central African Republic' , country: 'Central African Republic' },
      {cid: 'Chad' , country: 'Chad' },
      {cid: 'Chile' , country: 'Chile' },
      {cid: 'China' , country: 'China' },
      {cid: 'Colombia' , country: 'Colombia' },
      {cid: 'Comoros' , country: 'Comoros' },
      {cid: 'Democratic Republic of the Congo' , country: 'Democratic Republic of the Congo' },
      {cid: 'Republic of the Congo' , country: 'Republic of the Congo' },
      {cid: 'Costa Rica' , country: 'Costa Rica' },
      {cid: 'Croatia' , country: 'Croatia' },
      {cid: 'Cuba' , country: 'Cuba' },
      {cid: 'Cyprus' , country: 'Cyprus' },
      {cid: 'Czech Republic' , country: 'Czech Republic' },
      {cid: 'Denmark' , country: 'Denmark' },
      {cid: 'Djibouti' , country: 'Djibouti' },
      {cid: 'Dominica' , country: 'Dominica' },
      {cid: 'Dominican Republic' , country: 'Dominican Republic' },
      {cid: 'East Timor' , country: 'East Timor' },
      {cid: 'Ecuador' , country: 'Ecuador' },
      {cid: 'Egypt' , country: 'Egypt' },
      {cid: 'El Salvador' , country: 'El Salvador' },
      {cid: 'Equatorial Guinea' , country: 'Equatorial Guinea' },
      {cid: 'Eritrea' , country: 'Eritrea' },
      {cid: 'Estonia' , country: 'Estonia' },
      {cid: 'Ethiopia' , country: 'Ethiopia' },
      {cid: 'Fiji' , country: 'Fiji' },
      {cid: 'Finland' , country: 'Finland' },
      {cid: 'France' , country: 'France' },
      {cid: 'Gabon' , country: 'Gabon' },
      {cid: 'The Gambia' , country: 'Gambia, The' },
      {cid: 'Georgia' , country: 'Georgia' },
      {cid: 'Germany' , country: 'Germany' },
      {cid: 'Ghana' , country: 'Ghana' },
      {cid: 'Greece' , country: 'Greece' },
      {cid: 'Grenada' , country: 'Grenada' },
      {cid: 'Guatemala' , country: 'Guatemala' },
      {cid: 'Guinea' , country: 'Guinea' },
      {cid: 'Guinea-Bissau' , country: 'Guinea-Bissau' },
      {cid: 'Guyana' , country: 'Guyana' },
      {cid: 'Haiti' , country: 'Haiti' },
      {cid: 'Honduras' , country: 'Honduras' },
      {cid: 'Hungary' , country: 'Hungary' },
      {cid: 'Iceland' , country: 'Iceland' },
      {cid: 'India' , country: 'India' },
      {cid: 'Indonesia' , country: 'Indonesia' },
      {cid: 'Iran' , country: 'Iran' },
      {cid: 'Iraq' , country: 'Iraq' },
      {cid: 'Republic of Ireland' , country: 'Republic of Ireland' },
      {cid: 'Israel' , country: 'Israel' },
      {cid: 'Italy' , country: 'Italy' },
      {cid: 'Ivory Coast' , country: 'Ivory Coast' },
      {cid: 'Jamaica' , country: 'Jamaica' },
      {cid: 'Japan' , country: 'Japan' },
      {cid: 'Jordan' , country: 'Jordan' },
      {cid: 'Kazakhstan' , country: 'Kazakhstan' },
      {cid: 'Kenya' , country: 'Kenya' },
      {cid: 'Kiribati' , country: 'Kiribati' },
      {cid: 'North Korea' , country: 'North Korea' },
      {cid: 'South Korea ' , country: 'South Korea ' },
      {cid: 'Kuwait' , country: 'Kuwait' },
      {cid: 'Kyrgyzstan' , country: 'Kyrgyzstan' },
      {cid: 'Laos' , country: 'Laos' },
      {cid: 'Latvia' , country: 'Latvia' },
      {cid: 'Lebanon' , country: 'Lebanon' },
      {cid: 'Lesotho' , country: 'Lesotho' },
      {cid: 'Liberia' , country: 'Liberia' },
      {cid: 'Libya' , country: 'Libya' },
      {cid: 'Liechtenstein' , country: 'Liechtenstein' },
      {cid: 'Lithuania' , country: 'Lithuania' },
      {cid: 'Luxembourg' , country: 'Luxembourg' },
      {cid: 'Republic of Macedonia ' , country: 'Republic of Macedonia ' },
      {cid: 'Madagascar' , country: 'Madagascar' },
      {cid: 'Malawi' , country: 'Malawi' },
      {cid: 'Malaysia' , country: 'Malaysia' },
      {cid: 'Maldives' , country: 'Maldives' },
      {cid: 'Mali' , country: 'Mali' },
      {cid: 'Malta' , country: 'Malta' },
      {cid: 'Marshall Islands' , country: 'Marshall Islands' },
      {cid: 'Mauritania' , country: 'Mauritania' },
      {cid: 'Mauritius' , country: 'Mauritius' },
      {cid: 'Mexico' , country: 'Mexico' },
      {cid: 'Federated States of Micronesia' , country: 'Federated States of Micronesia' },
      {cid: 'Moldova' , country: 'Moldova' },
      {cid: 'Monaco' , country: 'Monaco' },
      {cid: 'Mongolia' , country: 'Mongolia' },
      {cid: 'Montenegro' , country: 'Montenegro' },
      {cid: 'Morocco' , country: 'Morocco' },
      {cid: 'Mozambique' , country: 'Mozambique' },
      {cid: 'Namibia' , country: 'Namibia' },
      {cid: 'Nauru' , country: 'Nauru' },
      {cid: 'Nepal' , country: 'Nepal' },
      {cid: 'Kingdom of the Netherlands' , country: 'Kingdom of the Netherlands' },
      {cid: 'New Zealand' , country: 'New Zealand' },
      {cid: 'Nicaragua' , country: 'Nicaragua' },
      {cid: 'Niger' , country: 'Niger' },
      {cid: 'Nigeria' , country: 'Nigeria' },
      {cid: 'Norway' , country: 'Norway' },
      {cid: 'Oman' , country: 'Oman' },
      {cid: 'Pakistan' , country: 'Pakistan' },
      {cid: 'Palau' , country: 'Palau' },
      {cid: 'State of Palestine' , country: 'State of Palestine' },
      {cid: 'Panama' , country: 'Panama' },
      {cid: 'Papua New Guinea' , country: 'Papua New Guinea' },
      {cid: 'Paraguay' , country: 'Paraguay' },
      {cid: 'Peru' , country: 'Peru' },
      {cid: 'Philippines' , country: 'Philippines' },
      {cid: 'Poland' , country: 'Poland' },
      {cid: 'Portugal' , country: 'Portugal' },
      {cid: 'Qatar' , country: 'Qatar' },
      {cid: 'Romania' , country: 'Romania' },
      {cid: 'Russia' , country: 'Russia' },
      {cid: 'Rwanda' , country: 'Rwanda' },
      {cid: 'Saint Kitts and Nevis' , country: 'Saint Kitts and Nevis' },
      {cid: 'Saint Lucia' , country: 'Saint Lucia' },
      {cid: 'Saint Vincent and the Grenadines' , country: 'Saint Vincent and the Grenadines' },
      {cid: 'Samoa' , country: 'Samoa' },
      {cid: 'San Marino' , country: 'San Marino' },
      {cid: 'Sao Tom&eacute; and Principe' , country: 'Sao Tom&eacute; and Principe' },
      {cid: 'Saudi Arabia' , country: 'Saudi Arabia' },
      {cid: 'Senegal' , country: 'Senegal' },
      {cid: 'Serbia' , country: 'Serbia' },
      {cid: 'Seychelles' , country: 'Seychelles' },
      {cid: 'Sierra Leone' , country: 'Sierra Leone' },
      {cid: 'Singapore' , country: 'Singapore' },
      {cid: 'Slovakia' , country: 'Slovakia' },
      {cid: 'Slovenia' , country: 'Slovenia' },
      {cid: 'Solomon Islands' , country: 'Solomon Islands' },
      {cid: 'Somalia' , country: 'Somalia' },
      {cid: 'South Africa' , country: 'South Africa' },
      {cid: 'South Sudan' , country: 'South Sudan' },
      {cid: 'Spain' , country: 'Spain' },
      {cid: 'Sri Lanka' , country: 'Sri Lanka' },
      {cid: 'Sudan' , country: 'Sudan' },
      {cid: 'Suriname' , country: 'Suriname' },
      {cid: 'Swaziland' , country: 'Swaziland' },
      {cid: 'Sweden' , country: 'Sweden' },
      {cid: 'Switzerland' , country: 'Switzerland' },
      {cid: 'Syria' , country: 'Syria' },
      {cid: 'Tajikistan' , country: 'Tajikistan' },
      {cid: 'Tanzania' , country: 'Tanzania' },
      {cid: 'Thailand' , country: 'Thailand' },
      {cid: 'Togo' , country: 'Togo' },
      {cid: 'Tonga' , country: 'Tonga' },
      {cid: 'Trinidad and Tobago' , country: 'Trinidad and Tobago' },
      {cid: 'Tunisia' , country: 'Tunisia' },
      {cid: 'Turkey' , country: 'Turkey' },
      {cid: 'Turkmenistan' , country: 'Turkmenistan' },
      {cid: 'Tuvalu' , country: 'Tuvalu' },
      {cid: 'Uganda' , country: 'Uganda' },
      {cid: 'Ukraine' , country: 'Ukraine' },
      {cid: 'United Arab Emirates' , country: 'United Arab Emirates' },
      {cid: 'United Kingdom' , country: 'United Kingdom' },
      {cid: 'United States' , country: 'United States of America' },
      {cid: 'Uruguay' , country: 'Uruguay' },
      {cid: 'Uzbekistan' , country: 'Uzbekistan' },
      {cid: 'Vanuatu' , country: 'Vanuatu' },
      {cid: 'Vatican City' , country: 'Vatican City' },
      {cid: 'Venezuela' , country: 'Venezuela' },
      {cid: 'Vietnam' , country: 'Vietnam' },
      {cid: 'Yemen' , country: 'Yemen' },
      {cid: 'Zambia' , country: 'Zambia' },
      {cid: 'Zimbabwe' , country: 'Zimbabwe' }
  ]
});